version: '3'

volumes:
  neo4j-data:
    driver: local

services:
  neo4j-server:
    image: neo4j:4.0
    container_name: shareforce-neo4jphp
    environment:
      NEO4J_AUTH: "neo4j/shareforce"
      NEO4J_dbms_default__database: "shareforce"
      NEO4J_dbms_default__listen__address: "0.0.0.0"
      NEO4J_dbms_connector_bolt_advertised__address: "shareforce-neo4jphp.docker:7687"
      NEO4J_dbms_connector_https_enabled: "false"
    volumes:
      - neo4j-data:/data
