site_name: neo4jphp
site_description: 'A PHP >= 7.4 library to work with Neo4j'

repo_url: 'https://github.com/shareforcelegal/neo4jphp'

docs_dir: docs/book
site_dir: docs/html

nav:
  - Introduction: index.md
  - "Quick Start": quick-start.md
