name: continuous-integration

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
        deps:
          - "highest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.deps }}"

      - name: "Run PHP_CodeSniffer"
        run: "vendor/bin/phpcs"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"

      - name: "Run PHPStan"
        run: "vendor/bin/phpstan"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-${{ matrix.deps }}-${{ matrix.php-version }}-coverage"
          path: "coverage*.xml"
